<div class="teamitem"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="320" height="320"/>
        <div class="wrap">
            <div><span class="h"></span><span class="v"></span></div>
        </div>
    </a>
    <div class="teaminfo">
        <p class="title"><a href="[field:arcurl/]">[field:title/]</a></p>
        <p class="description">[field:description function='cn_substr(@me,150)'/]...</p>
    </div>
    <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a></div>