<li style="background-image:url(/templets/cloud_23/images/1462382314720.jpg)" class="active">
    <div id="tempImage_0"></div>
    <video width="100%" height="100%" autoplay="" loop="" preload="auto" class="slider-video"
           style="width:100%; height:auto;">
        <source src="" type="video/mp4"></source>
    </video>
    <div class="mask"></div>
    <a target="_blank" href="http://www.22vd.com/">
        <div>
            <p class="title ellipsis">Welcome To Fafa guanwang</p>
            <p class="subtitle">你要明白人与人之间都是互不相欠 你在需要对方时他未能够及时出现 这并不是不在乎 而是所谓的错过了最合适的时间来抚平你的不安 而我们依然需要自己独自来克服眼前的困难
                靠自己永远都是最终的选择 无论你多需要关心 无论你正在经历着多大的苦痛 看一看四周无人 你就要逼自己成长 知道吗</p>
        </div>
        <div class="sliderArrow fa fa-angle-down"></div>
    </a></li>