<?php
$z[0] = Array("arcurl", "", 92, 107);
$z[0][4] = array();
$z[1] = Array("pubdate", "", 250, 296);
$z[1][4] = array();
$z[1][4]['function'] = "strftime(\"%Y\",@me)";
$z[2] = Array("pubdate", "", 336, 385);
$z[2][4] = array();
$z[2][4]['function'] = "strftime(\"%m-%d\",@me)";
$z[3] = Array("title", "", 435, 449);
$z[3][4] = array();
$z[4] = Array("description", "", 549, 599);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,150)";
$z[5] = Array("litpic", "", 723, 738);
$z[5][4] = array();
$z[6] = Array("arcurl", "", 779, 794);
$z[6][4] = array();

?>