<li class="projectitem"><a href="[field:arcurl/]" target="_blank">
        <div class="project_img"><img src="[field:litpic/]" width="500" height="320"/></div>
        <div class="project_info">
            <div>
                <p class="title">[field:title/]</p>
                <p class="subtitle">[field:typename/]</p>
            </div>
        </div>
    </a> <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a>
</li>