<li id="serviceitem_[field:global name=autoindex runphp=" yes"]@me=@me-1;[/field:global]" class="serviceitem wow"><a
        href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="320" height="120"/>
    <div>
        <p class="title">[field:title/]</p>
        <p class="description">[field:description function='cn_substr(@me,50)'/]...</p>
    </div>
</a> <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a> </li>