<?php
$z[0] = Array("id", "", 101, 112);
$z[0][4] = array();
$z[1] = Array("pubdate", "", 184, 233);
$z[1][4] = array();
$z[1][4]['function'] = "strftime(\"%m-%d\",@me)";
$z[2] = Array("pubdate", "", 271, 317);
$z[2][4] = array();
$z[2][4]['function'] = "strftime(\"%Y\",@me)";
$z[3] = Array("title", "", 425, 439);
$z[3][4] = array();
$z[4] = Array("description", "", 484, 533);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,50)";

?>