<li id="newsitem_0" class="wow newstitem left"><a class="newscontent" target="_blank" href="[field:arcurl/]">
        <div class="news_wrapper">
            <div class="newsbody">
                <p class="date"><span
                            class="md">[field:pubdate function='strftime("%Y",@me)'/]<span>-</span></span><span
                            class="year">[field:pubdate function='strftime("%m-%d",@me)'/]</span></p>
                <p class="title">[field:title/]</p>
                <div class="separator"></div>
                <p class="description">[field:description function='cn_substr(@me,100)'/]...</p>
            </div>
        </div>
        <div class="newsimg" style="background-image:url([field:litpic/])"></div>
    </a> <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a></li>