<?php
$z[0] = Array("field", "(@me==\"\")? @me=\" class='active'\":@me=\"\";", 167, 257);
$z[0][4] = array();
$z[0][4]['name'] = "typeid";
$z[0][4]['runphp'] = "yes";
$z[1] = Array("channelartlist", "\r\n      <li class=\"navitem\"><a {dede:field name='currentstyle'/} href=\"{dede:field name='typeurl'/}\" >{dede:field name='typename'/}</a>\r\n        <ul class=\"subnav\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ", 305, 715);
$z[1][4] = array();
$z[1][4]['row'] = "10";
$z[1][4]['typeid'] = "top";

?>