<?php
$z[0] = Array("field", "", 369, 388);
$z[0][4] = array();
$z[0][4]['name'] = "title";
$z[1] = Array("global", "", 389, 415);
$z[1][4] = array();
$z[1][4]['name'] = "cfg_webname";
$z[2] = Array("field", "", 456, 485);
$z[2][4] = array();
$z[2][4]['name'] = "keywords";
$z[3] = Array("field", "", 525, 583);
$z[3][4] = array();
$z[3][4]['name'] = "description";
$z[3][4]['function'] = "html2text(@me)";
$z[4] = Array("field", "", 1584, 1606);
$z[4][4] = array();
$z[4][4]['name'] = "typename";
$z[5] = Array("list", "\r\n          <li class=\"teamitem wow fadeIn\"><a href=\"view.php?aid=[field:id/]\">\r\n            <div id=\"team_img\"><img src=\"[field:litpic/]\" width=\"90\" height=\"90\" /></div>\r\n            <div class=\"teaminfo\">\r\n              <div class=\"header\">\r\n                <p class=\"title\">[field:title/]</p>\r\n                <p class=\"subtitle\"></p>\r\n              </div>\r\n              <p class=\"description\">[field:description function='cn_substr(@me,150)'/]...</p>\r\n            </div>\r\n            </a></li>\r\n          ", 1700, 2260);
$z[5][4] = array();
$z[5][4]['pagesize'] = "9";
$z[5][4]['titlelen'] = "36";
$z[6] = Array("pagelist", "", 2331, 2380);
$z[6][4] = array();
$z[6][4]['listitem'] = "pre,next";
$z[6][4]['listsize'] = "5";
$z[7] = Array("include", "", 2443, 2480);
$z[7][4] = array();
$z[7][4]['filename'] = "foot_m.htm";
$z[8] = Array("include", "", 2548, 2585);
$z[8][4] = array();
$z[8][4]['filename'] = "left_m.htm";

?>