apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: centos-ssh
spec:
  serviceName: centos-ssh
  replicas: 1
  selector:
    matchLabels:
      app: centos-ssh
  template:
    metadata:
      labels:
        app: centos-ssh
    spec:
      containers:
      - image: daocloud.io/library/centos:7.6.1810
        name: centos-ssh
        command: ["/bin/sh","-c","top -b"]

        # kubectl apply -f centos.yaml
        1