<?php
$z[0] = Array("global", "@me=@me-1;", 17, 84);
$z[0][4] = array();
$z[0][4]['name'] = "autoindex";
$z[0][4]['runphp'] = "yes";
$z[1] = Array("arcurl", "", 158, 173);
$z[1][4] = array();
$z[2] = Array("pubdate", "", 316, 362);
$z[2][4] = array();
$z[2][4]['function'] = "strftime(\"%Y\",@me)";
$z[3] = Array("pubdate", "", 402, 451);
$z[3][4] = array();
$z[3][4]['function'] = "strftime(\"%m-%d\",@me)";
$z[4] = Array("title", "", 501, 515);
$z[4][4] = array();
$z[5] = Array("description", "", 615, 665);
$z[5][4] = array();
$z[5][4]['function'] = "cn_substr(@me,150)";
$z[6] = Array("litpic", "", 789, 804);
$z[6][4] = array();
$z[7] = Array("arcurl", "", 845, 860);
$z[7][4] = array();

?>