<?php
$z[0] = Array("arcurl", "", 31, 46);
$z[0][4] = array();
$z[1] = Array("litpic", "", 58, 73);
$z[1][4] = array();
$z[2] = Array("arcurl", "", 323, 338);
$z[2][4] = array();
$z[3] = Array("title", "", 340, 354);
$z[3][4] = array();
$z[4] = Array("description", "", 401, 451);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,150)";
$z[5] = Array("arcurl", "", 501, 516);
$z[5][4] = array();

?>