<?php
$z[0] = Array("arcurl", "", 94, 109);
$z[0][4] = array();
$z[1] = Array("pubdate", "", 240, 286);
$z[1][4] = array();
$z[1][4]['function'] = "strftime(\"%Y\",@me)";
$z[2] = Array("pubdate", "", 326, 375);
$z[2][4] = array();
$z[2][4]['function'] = "strftime(\"%m-%d\",@me)";
$z[3] = Array("title", "", 421, 435);
$z[3][4] = array();
$z[4] = Array("description", "", 527, 577);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,250)";
$z[5] = Array("litpic", "", 689, 704);
$z[5][4] = array();
$z[6] = Array("arcurl", "", 741, 756);
$z[6][4] = array();

?>