<?php
$z[0] = Array("id", "", 79, 90);
$z[0][4] = array();
$z[1] = Array("pubdate", "", 158, 207);
$z[1][4] = array();
$z[1][4]['function'] = "strftime(\"%m-%d\",@me)";
$z[2] = Array("pubdate", "", 243, 289);
$z[2][4] = array();
$z[2][4]['function'] = "strftime(\"%Y\",@me)";
$z[3] = Array("title", "", 391, 405);
$z[3][4] = array();
$z[4] = Array("description", "", 448, 498);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,150)";

?>