<li class="serviceitem wow fadeIn"><a href="view.php?aid=[field:id/]" target="_blank"><img src="[field:litpic/]"
                                                                                           width="320"
                                                                                           height="120"/></a>
    <div>
        <p class="title ellipsis">[field:title/]</p>
        <p class="description">[field:description function='cn_substr(@me,150)'/]...</p>
    </div>
</li>
<li class="line"></li>