<li id="projectitem_[field:global name=autoindex runphp=" yes"]@me=@me+1;[/field:global]" class="projectitem wow"> <a
        href="[field:arcurl/]" class="projectitem_content" target="_blank">
    <div class="projectitem_wrapper">
        <div class="project_img"><img src="[field:litpic/]" width="500" height="320"/></div>
        <div class="project_info">
            <div>
                <p class="title">[field:title/]</p>
                <p class="subtitle">[field:typename/]</p>
            </div>
        </div>
    </div>
</a> </li>