<li class="navitem "><a href="javascript:;" href="list.php?tid=[field:id/]" class="hassub"><span
                class="circle transform"></span>{dede:field name='typename'/} <span class="more"><span class="h"></span><span
                    class="h v transform"></span></span> </a>
    <ul class="subnav transform" data-height="auto">
        {dede:channel type='son' noself='yes'}
        <li><a href="list.php?tid=[field:id/]">[field:typename/]</a></li>
        {/dede:channel}
    </ul>
</li>