<?php
$z[0] = Array("field", "", 369, 388);
$z[0][4] = array();
$z[0][4]['name'] = "title";
$z[1] = Array("global", "", 389, 415);
$z[1][4] = array();
$z[1][4]['name'] = "cfg_webname";
$z[2] = Array("field", "", 456, 485);
$z[2][4] = array();
$z[2][4]['name'] = "keywords";
$z[3] = Array("field", "", 525, 583);
$z[3][4] = array();
$z[3][4]['name'] = "description";
$z[3][4]['function'] = "html2text(@me)";
$z[4] = Array("field", "", 1779, 1800);
$z[4][4] = array();
$z[4][4]['name'] = "content";
$z[5] = Array("include", "", 3633, 3670);
$z[5][4] = array();
$z[5][4]['filename'] = "foot_m.htm";
$z[6] = Array("include", "", 3690, 3727);
$z[6][4] = array();
$z[6][4]['filename'] = "head_m.htm";

?>