<?php
$z[0] = Array("field", "", 369, 388);
$z[0][4] = array();
$z[0][4]['name'] = "title";
$z[1] = Array("global", "", 389, 415);
$z[1][4] = array();
$z[1][4]['name'] = "cfg_webname";
$z[2] = Array("field", "", 456, 478);
$z[2][4] = array();
$z[2][4]['name'] = "keywords";
$z[3] = Array("field", "", 518, 569);
$z[3][4] = array();
$z[3][4]['name'] = "description";
$z[3][4]['function'] = "html2text(@me)";
$z[4] = Array("field", "", 1575, 1594);
$z[4][4] = array();
$z[4][4]['name'] = "title";
$z[5] = Array("field", "", 1709, 1727);
$z[5][4] = array();
$z[5][4]['name'] = "body";
$z[6] = Array("include", "", 1825, 1862);
$z[6][4] = array();
$z[6][4]['filename'] = "foot_m.htm";
$z[7] = Array("include", "", 1882, 1919);
$z[7][4] = array();
$z[7][4]['filename'] = "head_m.htm";

?>