<li class="teamitem wow fadeIn"><a href="view.php?aid=[field:id/]">
        <div id="mteam_img"><img src="[field:litpic/]" width="90" height="90"/></div>
        <div class="teaminfo">
            <div class="header">
                <p class="title">[field:title/]</p>
                <p class="subtitle"></p>
            </div>
            <p class="description">[field:description function='cn_substr(@me,150)'/]...</p>
        </div>
    </a></li>