<?php
$z[0] = Array("arcurl", "", 105, 120);
$z[0][4] = array();
$z[1] = Array("litpic", "", 148, 163);
$z[1][4] = array();
$z[2] = Array("arcurl", "", 291, 306);
$z[2][4] = array();
$z[3] = Array("title", "", 308, 322);
$z[3][4] = array();
$z[4] = Array("description", "", 421, 471);
$z[4][4] = array();
$z[4][4]['function'] = "cn_substr(@me,100)";
$z[5] = Array("arcurl", "", 529, 544);
$z[5][4] = array();

?>