<?php
$z[0] = Array("global", "@me=@me+1;", 17, 84);
$z[0][4] = array();
$z[0][4]['name'] = "autoindex";
$z[0][4]['runphp'] = "yes";
$z[1] = Array("arcurl", "", 171, 186);
$z[1][4] = array();
$z[2] = Array("litpic", "", 214, 229);
$z[2][4] = array();
$z[3] = Array("arcurl", "", 357, 372);
$z[3][4] = array();
$z[4] = Array("title", "", 374, 388);
$z[4][4] = array();
$z[5] = Array("description", "", 487, 537);
$z[5][4] = array();
$z[5][4]['function'] = "cn_substr(@me,100)";
$z[6] = Array("arcurl", "", 595, 610);
$z[6][4] = array();

?>