<?php
$z[0] = Array("type", "<a href=\"javascript:;\" class=\"hassub\"><span class=\"circle transform\"></span>[field:typename /]<span class=\"more\"><span class=\"h\"></span><span class=\"h v transform\"></span></span> </a>", 517, 734);
$z[0][4] = array();
$z[0][4]['typeid'] = "1";
$z[1] = Array("channel", "\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n        ", 800, 936);
$z[1][4] = array();
$z[1][4]['type'] = "son";
$z[1][4]['typeid'] = "1";
$z[2] = Array("type", "<a href=\"javascript:;\" class=\"hassub\"><span class=\"circle transform\"></span>[field:typename /]<span class=\"more\"><span class=\"h\"></span><span class=\"h v transform\"></span></span> </a>", 988, 1205);
$z[2][4] = array();
$z[2][4]['typeid'] = "5";
$z[3] = Array("channel", "\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n        ", 1271, 1407);
$z[3][4] = array();
$z[3][4]['type'] = "son";
$z[3][4]['typeid'] = "5";
$z[4] = Array("type", "<li class=\"navitem \"><a  href=\"list.php?tid=[field:id/]\" class=\"hassub\"><span class=\"circle transform\"></span>[field:typename /] </a> </li>", 1439, 1612);
$z[4][4] = array();
$z[4][4]['typeid'] = "8";
$z[5] = Array("type", "<li class=\"navitem \"><a  href=\"list.php?tid=[field:id/]\" class=\"hassub\"><span class=\"circle transform\"></span>[field:typename /] </a> </li>", 1618, 1791);
$z[5][4] = array();
$z[5][4]['typeid'] = "9";
$z[6] = Array("type", "<li class=\"navitem \"><a  href=\"list.php?tid=[field:id/]\" class=\"hassub\"><span class=\"circle transform\"></span>[field:typename /] </a> </li>", 1797, 1971);
$z[6][4] = array();
$z[6][4]['typeid'] = "11";

?>