<?php
global $cfg_Cs;
$cfg_Cs = array();
$cfg_Cs[1] = array(0, 1, 1, '5Lqn5ZOB');
$cfg_Cs[2] = array(1, 1, 1, '5bu6562R6K6+6K6h');
$cfg_Cs[3] = array(1, 1, 1, '5bel5Lia6K6+6K6h');
$cfg_Cs[4] = array(1, 1, 1, '5a6k5YaF6K6+6K6h');
$cfg_Cs[5] = array(0, 1, 1, '5paw6Ze7');
$cfg_Cs[6] = array(5, 1, 1, '5YWs5Y+45paw6Ze7');
$cfg_Cs[7] = array(5, 1, 1, '6KGM5Lia5paw6Ze7');
$cfg_Cs[8] = array(0, 1, 1, '5Zui6Zif');
$cfg_Cs[9] = array(0, 1, 1, '5pyN5Yqh');
$cfg_Cs[11] = array(0, 1, 1, '5YWz5LqO');
?>